version: '2'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - "/src/app"
    ports:
      - "49160:8080"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
    ports:
      - "9200:9200"
    environment:
      - cluster.name=neurolex-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.watcher.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
  kibana:
    image: docker.elastic.co/kibana/kibana:5.4.0
    ports:
      - 5601:5601
    volumes:
      - "./kibana.yml:/usr/share/kibana/config/kibana.yml"